
package com.roytuts.soapSetClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZZCONTEA_SET_ONLINEPAYMENT", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/home/marziobiancardi/Documents/newWsdlPagamento/contea_set_payments_new.xml")
public class ZZCONTEASETONLINEPAYMENT_Service
    extends Service
{

    private final static URL ZZCONTEASETONLINEPAYMENT_WSDL_LOCATION;
    private final static WebServiceException ZZCONTEASETONLINEPAYMENT_EXCEPTION;
    private final static QName ZZCONTEASETONLINEPAYMENT_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZZCONTEA_SET_ONLINEPAYMENT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/marziobiancardi/Documents/newWsdlPagamento/contea_set_payments_new.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZZCONTEASETONLINEPAYMENT_WSDL_LOCATION = url;
        ZZCONTEASETONLINEPAYMENT_EXCEPTION = e;
    }

    public ZZCONTEASETONLINEPAYMENT_Service() {
        super(__getWsdlLocation(), ZZCONTEASETONLINEPAYMENT_QNAME);
    }

    public ZZCONTEASETONLINEPAYMENT_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZZCONTEASETONLINEPAYMENT_QNAME, features);
    }

    public ZZCONTEASETONLINEPAYMENT_Service(URL wsdlLocation) {
        super(wsdlLocation, ZZCONTEASETONLINEPAYMENT_QNAME);
    }

    public ZZCONTEASETONLINEPAYMENT_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZZCONTEASETONLINEPAYMENT_QNAME, features);
    }

    public ZZCONTEASETONLINEPAYMENT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZZCONTEASETONLINEPAYMENT_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZZCONTEASETONLINEPAYMENT
     */
    @WebEndpoint(name = "SetPayment")
    public ZZCONTEASETONLINEPAYMENT getSetPayment() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "SetPayment"), ZZCONTEASETONLINEPAYMENT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZZCONTEASETONLINEPAYMENT
     */
    @WebEndpoint(name = "SetPayment")
    public ZZCONTEASETONLINEPAYMENT getSetPayment(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "SetPayment"), ZZCONTEASETONLINEPAYMENT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZZCONTEASETONLINEPAYMENT_EXCEPTION!= null) {
            throw ZZCONTEASETONLINEPAYMENT_EXCEPTION;
        }
        return ZZCONTEASETONLINEPAYMENT_WSDL_LOCATION;
    }

}
