package com.alpenite.tea.wdslfascicolo;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T12:49:17.896+02:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "SVCZPTGETFASCICOLO",
                  wsdlLocation = "file:/root/namespaceSap/PRD_ZPTGETFASCICOLO.wsdl",
                  targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class SvcZptGetFascicolo extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "SVCZPTGETFASCICOLO");
    public final static QName BNDZPTGETFASCICOLO = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "BNDZPTGETFASCICOLO");
    static {
        URL url = null;
        try {
            url = new URL("file:/root/namespaceSap/PRD_ZPTGETFASCICOLO.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SvcZptGetFascicolo.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/var/folders/jr/wg4px6q567z9pnd37nln7vbc0000gn/T/tempdir1574629698737589467.tmp/QTA_ZPTGETFASCICOLO_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SvcZptGetFascicolo(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SvcZptGetFascicolo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SvcZptGetFascicolo() {
        super(WSDL_LOCATION, SERVICE);
    }

    public SvcZptGetFascicolo(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public SvcZptGetFascicolo(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SvcZptGetFascicolo(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ZPTGETFASCICOLO
     */
    @WebEndpoint(name = "BNDZPTGETFASCICOLO")
    public ZPTGETFASCICOLO getBNDZPTGETFASCICOLO() {
        return super.getPort(BNDZPTGETFASCICOLO, ZPTGETFASCICOLO.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZPTGETFASCICOLO
     */
    @WebEndpoint(name = "BNDZPTGETFASCICOLO")
    public ZPTGETFASCICOLO getBNDZPTGETFASCICOLO(WebServiceFeature... features) {
        return super.getPort(BNDZPTGETFASCICOLO, ZPTGETFASCICOLO.class, features);
    }

}
