
package com.alpenite.tea.wdslfascicolo;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T12:49:17.862+02:00
 * Generated source version: 3.2.4
 */

@WebFault(name = "ZptGetFascicolo.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZptGetFascicoloException extends Exception {

    private com.alpenite.tea.wdslfascicolo.ZptGetFascicoloRfcException zptGetFascicoloException;

    public ZptGetFascicoloException() {
        super();
    }

    public ZptGetFascicoloException(String message) {
        super(message);
    }

    public ZptGetFascicoloException(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ZptGetFascicoloException(String message, com.alpenite.tea.wdslfascicolo.ZptGetFascicoloRfcException zptGetFascicoloException) {
        super(message);
        this.zptGetFascicoloException = zptGetFascicoloException;
    }

    public ZptGetFascicoloException(String message, com.alpenite.tea.wdslfascicolo.ZptGetFascicoloRfcException zptGetFascicoloException, java.lang.Throwable cause) {
        super(message, cause);
        this.zptGetFascicoloException = zptGetFascicoloException;
    }

    public com.alpenite.tea.wdslfascicolo.ZptGetFascicoloRfcException getFaultInfo() {
        return this.zptGetFascicoloException;
    }
}
