
package com.alpenite.tea.wdslfascicolo;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T12:49:17.893+02:00
 * Generated source version: 3.2.4
 *
 */

public class ZPTGETFASCICOLO_BNDZPTGETFASCICOLO_Server{

    protected ZPTGETFASCICOLO_BNDZPTGETFASCICOLO_Server() throws java.lang.Exception {
        System.out.println("Starting Server");
        Object implementor = new BNDZPTGETFASCICOLOImpl();
        String address = "http://d-q-isu-as.teaspa.lan:8020/sap/bc/srt/rfc/sap/zpt_get_fascicolo/900/svczptgetfascicolo/bndzptgetfascicolo";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws java.lang.Exception {
        new ZPTGETFASCICOLO_BNDZPTGETFASCICOLO_Server();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}
