
package com.alpenite.tea.wdslfascicolo;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-04-28T12:49:17.788+02:00
 * Generated source version: 3.2.4
 *
 */
public final class ZPTGETFASCICOLO_BNDZPTGETFASCICOLO_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "SVCZPTGETFASCICOLO");

    private ZPTGETFASCICOLO_BNDZPTGETFASCICOLO_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SvcZptGetFascicolo.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SvcZptGetFascicolo ss = new SvcZptGetFascicolo(wsdlURL, SERVICE_NAME);
        ZPTGETFASCICOLO port = ss.getBNDZPTGETFASCICOLO();

        {
        System.out.println("Invoking zptGetFascicolo...");
        java.lang.String _zptGetFascicolo_iCc = "30139084";
        try {
            com.alpenite.tea.wdslfascicolo.ZptTyFascicolo _zptGetFascicolo__return = port.zptGetFascicolo(_zptGetFascicolo_iCc);
            System.out.println("zptGetFascicolo.result=" + _zptGetFascicolo__return);
            System.out.println(_zptGetFascicolo__return.item.get(0).definizIt);

        } catch (ZptGetFascicoloException e) {
            System.out.println("Expected exception: ZptGetFascicolo.Exception has occurred.");
            System.out.println(e.toString());
        }
            }

        System.exit(0);
    }

}
