
package com.roytuts.soap.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ZZCONTEA_GET_ONLINEPAYMENT", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", wsdlLocation = "file:/home/marziobiancardi/Documents/newWsdlPagamento/get_contea_new_wdsl.xml")
public class ZZCONTEAGETONLINEPAYMENT_Service
    extends Service
{

    private final static URL ZZCONTEAGETONLINEPAYMENT_WSDL_LOCATION;
    private final static WebServiceException ZZCONTEAGETONLINEPAYMENT_EXCEPTION;
    private final static QName ZZCONTEAGETONLINEPAYMENT_QNAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZZCONTEA_GET_ONLINEPAYMENT");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/home/marziobiancardi/Documents/newWsdlPagamento/get_contea_new_wdsl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ZZCONTEAGETONLINEPAYMENT_WSDL_LOCATION = url;
        ZZCONTEAGETONLINEPAYMENT_EXCEPTION = e;
    }

    public ZZCONTEAGETONLINEPAYMENT_Service() {
        super(__getWsdlLocation(), ZZCONTEAGETONLINEPAYMENT_QNAME);
    }

    public ZZCONTEAGETONLINEPAYMENT_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), ZZCONTEAGETONLINEPAYMENT_QNAME, features);
    }

    public ZZCONTEAGETONLINEPAYMENT_Service(URL wsdlLocation) {
        super(wsdlLocation, ZZCONTEAGETONLINEPAYMENT_QNAME);
    }

    public ZZCONTEAGETONLINEPAYMENT_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ZZCONTEAGETONLINEPAYMENT_QNAME, features);
    }

    public ZZCONTEAGETONLINEPAYMENT_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ZZCONTEAGETONLINEPAYMENT_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ZZCONTEAGETONLINEPAYMENT
     */
    @WebEndpoint(name = "GetPayment")
    public ZZCONTEAGETONLINEPAYMENT getGetPayment() {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "GetPayment"), ZZCONTEAGETONLINEPAYMENT.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ZZCONTEAGETONLINEPAYMENT
     */
    @WebEndpoint(name = "GetPayment")
    public ZZCONTEAGETONLINEPAYMENT getGetPayment(WebServiceFeature... features) {
        return super.getPort(new QName("urn:sap-com:document:sap:soap:functions:mc-style", "GetPayment"), ZZCONTEAGETONLINEPAYMENT.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ZZCONTEAGETONLINEPAYMENT_EXCEPTION!= null) {
            throw ZZCONTEAGETONLINEPAYMENT_EXCEPTION;
        }
        return ZZCONTEAGETONLINEPAYMENT_WSDL_LOCATION;
    }

}
