
package com.roytuts.soap.client;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ZzconteaGetOnlinepayment.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZzconteaGetOnlinepaymentException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ZzconteaGetOnlinepaymentRfcException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ZzconteaGetOnlinepaymentException(String message, ZzconteaGetOnlinepaymentRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ZzconteaGetOnlinepaymentException(String message, ZzconteaGetOnlinepaymentRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.roytuts.soap.client.ZzconteaGetOnlinepaymentRfcException
     */
    public ZzconteaGetOnlinepaymentRfcException getFaultInfo() {
        return faultInfo;
    }

}
