
package com.alpenite.tea.communicationLayer.ws.isu;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ZptGetBpFromCc.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZptGetBpFromCcException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ZptGetBpFromCcRfcException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public ZptGetBpFromCcException(String message, ZptGetBpFromCcRfcException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public ZptGetBpFromCcException(String message, ZptGetBpFromCcRfcException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.test.teaalpenite.ZptGetBpFromCcRfcException
     */
    public ZptGetBpFromCcRfcException getFaultInfo() {
        return faultInfo;
    }

}
