
package com.alpenite.tea.communicationLayer.ws.isu;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCc;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ZWS_ISU_PORTAL", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ZWSISUPORTAL {


    /**
     * 
     * @param etMess
     * @param iAcqua
     * @param iPartner
     * @param iZwstan
     * @param iVertrag
     * @param iId
     * @param eReturn
     */
    @WebMethod(operationName = "ZptAutolettura")
    @RequestWrapper(localName = "ZptAutolettura", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptAutolettura")
    @ResponseWrapper(localName = "ZptAutoletturaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptAutoletturaResponse")
    public void zptAutolettura(
        @WebParam(name = "IAcqua", targetNamespace = "")
        String iAcqua,
        @WebParam(name = "IId", targetNamespace = "")
        String iId,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "IZwstan", targetNamespace = "")
        String iZwstan,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param iDatato
     * @param etMess
     * @param etList
     * @param iPartner
     * @param iFlagSfatt
     * @param iFlagPa
     * @param iFlagEc
     * @param eReturn
     * @param iDatafrom
     * @param iCc
     */
    @WebMethod(operationName = "ZptCcListDett")
    @RequestWrapper(localName = "ZptCcListDett", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCcListDett")
    @ResponseWrapper(localName = "ZptCcListDettResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCcListDettResponse")
    public void zptCcListDett(
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "IDatafrom", targetNamespace = "")
        String iDatafrom,
        @WebParam(name = "IDatato", targetNamespace = "")
        String iDatato,
        @WebParam(name = "IFlagEc", targetNamespace = "")
        String iFlagEc,
        @WebParam(name = "IFlagPa", targetNamespace = "")
        String iFlagPa,
        @WebParam(name = "IFlagSfatt", targetNamespace = "")
        String iFlagSfatt,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtList> etList,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iSapObject
     * @param iPartner
     * @param eMimetyp
     * @param iArcDocId
     * @param eExt
     * @param eReturn
     * @param eName
     * @param eBin
     */
    @WebMethod(operationName = "ZptDownloadFile")
    @RequestWrapper(localName = "ZptDownloadFile", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDownloadFile")
    @ResponseWrapper(localName = "ZptDownloadFileResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDownloadFileResponse")
    public void zptDownloadFile(
        @WebParam(name = "IArcDocId", targetNamespace = "")
        String iArcDocId,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "ISapObject", targetNamespace = "")
        String iSapObject,
        @WebParam(name = "EBin", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<byte[]> eBin,
        @WebParam(name = "EExt", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eExt,
        @WebParam(name = "EMimetyp", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMimetyp,
        @WebParam(name = "EName", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eName,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iRegion
     * @param etCity
     * @param eReturn
     */
    @WebMethod(operationName = "ZptReadComune")
    @RequestWrapper(localName = "ZptReadComune", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptReadComune")
    @ResponseWrapper(localName = "ZptReadComuneResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptReadComuneResponse")
    public void zptReadComune(
        @WebParam(name = "IRegion", targetNamespace = "")
        String iRegion,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtCity", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtComuni> etCity,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iBpType
     * @param iPi
     * @param esBpData
     * @param iCf
     * @param iMail
     * @param eReturn
     * @param iCc
     */
    @WebMethod(operationName = "ZptCheckUsername")
    @RequestWrapper(localName = "ZptCheckUsername", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCheckUsername")
    @ResponseWrapper(localName = "ZptCheckUsernameResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCheckUsernameResponse")
    public void zptCheckUsername(
        @WebParam(name = "IBpType", targetNamespace = "")
        String iBpType,
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "ICf", targetNamespace = "")
        String iCf,
        @WebParam(name = "IMail", targetNamespace = "")
        String iMail,
        @WebParam(name = "IPi", targetNamespace = "")
        String iPi,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EsBpData", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStBpData> esBpData,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iPartner
     * @param itContract
     * @param eReturn
     * @param itCompany
     */
    @WebMethod(operationName = "ZptContractList")
    @RequestWrapper(localName = "ZptContractList", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractList")
    @ResponseWrapper(localName = "ZptContractListResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractListResponse")
    public void zptContractList(
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "ItCompany", targetNamespace = "")
        ZptTtCompanies itCompany,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess,
        @WebParam(name = "ItContract", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtContract> itContract);

    /**
     * 
     * @param iDatato
     * @param etMess
     * @param etList
     * @param iPartner
     * @param iFlagSfatt
     * @param iFlagPa
     * @param eReturn
     * @param iDatafrom
     */
    @WebMethod(operationName = "ZptContractListDett")
    @RequestWrapper(localName = "ZptContractListDett", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractListDett")
    @ResponseWrapper(localName = "ZptContractListDettResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractListDettResponse")
    public void zptContractListDett(
        @WebParam(name = "IDatafrom", targetNamespace = "")
        String iDatafrom,
        @WebParam(name = "IDatato", targetNamespace = "")
        String iDatato,
        @WebParam(name = "IFlagPa", targetNamespace = "")
        String iFlagPa,
        @WebParam(name = "IFlagSfatt", targetNamespace = "")
        String iFlagSfatt,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtList> etList,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param isRecapito
     * @param iPartner
     * @param isRid
     * @param iDr
     * @param iDd
     * @param eReturn
     * @param iCc
     */
    @WebMethod(operationName = "ZptCcDetail")
    @RequestWrapper(localName = "ZptCcDetail", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCcDetail")
    @ResponseWrapper(localName = "ZptCcDetailResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptCcDetailResponse")
    public void zptCcDetail(
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "IDd", targetNamespace = "")
        String iDd,
        @WebParam(name = "IDr", targetNamespace = "")
        String iDr,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess,
        @WebParam(name = "IsRecapito", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStRecapito> isRecapito,
        @WebParam(name = "IsRid", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStRid> isRid);

    /**
     * 
     * @param esDc
     * @param etMess
     * @param iPartner
     * @param iFlagDc
     * @param esPod
     * @param etRiduzioni
     * @param esInfo
     * @param iVertrag
     * @param eReturn
     * @param iFlagPod
     * @param iCc
     * @param iFlagInfo
     */
    @WebMethod(operationName = "ZptContractDetail")
    @RequestWrapper(localName = "ZptContractDetail", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractDetail")
    @ResponseWrapper(localName = "ZptContractDetailResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptContractDetailResponse")
    public void zptContractDetail(
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "IFlagDc", targetNamespace = "")
        String iFlagDc,
        @WebParam(name = "IFlagInfo", targetNamespace = "")
        String iFlagInfo,
        @WebParam(name = "IFlagPod", targetNamespace = "")
        String iFlagPod,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EsDc", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStDc> esDc,
        @WebParam(name = "EsInfo", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStInfo> esInfo,
        @WebParam(name = "EsPod", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptStPod> esPod,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess,
        @WebParam(name = "EtRiduzioni", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtRiduzioni> etRiduzioni);

    /**
     * 
     * @param etMess
     * @param iBp
     * @param eMimetyp
     * @param eExt
     * @param eReturn
     * @param iCc
     * @param eBin
     * @param isRevoke
     */
    @WebMethod(operationName = "ZptDownloadForm")
    @RequestWrapper(localName = "ZptDownloadForm", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDownloadForm")
    @ResponseWrapper(localName = "ZptDownloadFormResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDownloadFormResponse")
    public void zptDownloadForm(
        @WebParam(name = "IBp", targetNamespace = "")
        String iBp,
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "IsRevoke", targetNamespace = "")
        String isRevoke,
        @WebParam(name = "EBin", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<byte[]> eBin,
        @WebParam(name = "EExt", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eExt,
        @WebParam(name = "EMimetyp", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMimetyp,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iPartner
     * @param ia
     * @param iFlagLetture
     * @param iDa
     * @param iFlagSac
     * @param iFlagSvuota
     * @param etLett
     * @param iVertrag
     * @param eReturn
     */
    @WebMethod(operationName = "ZptLettureSvuotamenti")
    @RequestWrapper(localName = "ZptLettureSvuotamenti", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptLettureSvuotamenti")
    @ResponseWrapper(localName = "ZptLettureSvuotamentiResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptLettureSvuotamentiResponse")
    public void zptLettureSvuotamenti(
        @WebParam(name = "IA", targetNamespace = "")
        String ia,
        @WebParam(name = "IDa", targetNamespace = "")
        String iDa,
        @WebParam(name = "IFlagLetture", targetNamespace = "")
        String iFlagLetture,
        @WebParam(name = "IFlagSac", targetNamespace = "")
        String iFlagSac,
        @WebParam(name = "IFlagSvuota", targetNamespace = "")
        String iFlagSvuota,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtLett", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtLett> etLett,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iPartner
     * @param iComCat
     * @param iSezUrb
     * @param iCodCat
     * @param iComAmm
     * @param iPartst
     * @param iPart
     * @param iSubal
     * @param iVertrag
     * @param eReturn
     * @param iTipopar
     */
    @WebMethod(operationName = "ZsrCadastralDataChange")
    @RequestWrapper(localName = "ZsrCadastralDataChange", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZsrCadastralDataChange")
    @ResponseWrapper(localName = "ZsrCadastralDataChangeResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZsrCadastralDataChangeResponse")
    public void zsrCadastralDataChange(
        @WebParam(name = "ICodCat", targetNamespace = "")
        String iCodCat,
        @WebParam(name = "IComAmm", targetNamespace = "")
        String iComAmm,
        @WebParam(name = "IComCat", targetNamespace = "")
        String iComCat,
        @WebParam(name = "IPart", targetNamespace = "")
        String iPart,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IPartst", targetNamespace = "")
        String iPartst,
        @WebParam(name = "ISezUrb", targetNamespace = "")
        String iSezUrb,
        @WebParam(name = "ISubal", targetNamespace = "")
        String iSubal,
        @WebParam(name = "ITipopar", targetNamespace = "")
        String iTipopar,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param iCc
     * @return
     *     returns java.lang.String
     * @throws ZptGetBpFromCcException
     */
    @WebMethod(operationName = "ZptGetBpFromCc")
    @WebResult(name = "EPartner", targetNamespace = "")
    @RequestWrapper(localName = "ZptGetBpFromCc", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptGetBpFromCc")
    @ResponseWrapper(localName = "ZptGetBpFromCcResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptGetBpFromCcResponse")
    public String zptGetBpFromCc(
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc)
        throws ZptGetBpFromCcException
    ;

    /**
     * 
     * @param etMess
     * @param iPartner
     * @param etBidoni
     * @param iVertrag
     * @param eReturn
     */
    @WebMethod(operationName = "ZptBidoni")
    @RequestWrapper(localName = "ZptBidoni", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptBidoni")
    @ResponseWrapper(localName = "ZptBidoniResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptBidoniResponse")
    public void zptBidoni(
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtBidoni", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtBidoni> etBidoni,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param eZzcontatto
     * @param iZzcontatto
     * @param eVertrag
     * @param iVertrag
     */
    @WebMethod(operationName = "ZptDettagliContatto")
    @RequestWrapper(localName = "ZptDettagliContatto", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDettagliContatto")
    @ResponseWrapper(localName = "ZptDettagliContattoResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDettagliContattoResponse")
    public void zptDettagliContatto(
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "IZzcontatto", targetNamespace = "")
        String iZzcontatto,
        @WebParam(name = "EVertrag", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eVertrag,
        @WebParam(name = "EZzcontatto", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eZzcontatto,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iPartner
     * @param etBidoni
     * @param iVertrag
     * @param eReturn
     */
    @WebMethod(operationName = "ZptSacchetti")
    @RequestWrapper(localName = "ZptSacchetti", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptSacchetti")
    @ResponseWrapper(localName = "ZptSacchettiResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptSacchettiResponse")
    public void zptSacchetti(
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IVertrag", targetNamespace = "")
        String iVertrag,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtBidoni", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtBidoni> etBidoni,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param iDatato
     * @param etMess
     * @param etList
     * @param iPartner
     * @param iFlagSfatt
     * @param iFlagPa
     * @param eReturn
     * @param iXblnr
     * @param iDatafrom
     */
    @WebMethod(operationName = "ZptDettagliFattura")
    @RequestWrapper(localName = "ZptDettagliFattura", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDettagliFattura")
    @ResponseWrapper(localName = "ZptDettagliFatturaResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptDettagliFatturaResponse")
    public void zptDettagliFattura(
        @WebParam(name = "IDatafrom", targetNamespace = "")
        String iDatafrom,
        @WebParam(name = "IDatato", targetNamespace = "")
        String iDatato,
        @WebParam(name = "IFlagPa", targetNamespace = "")
        String iFlagPa,
        @WebParam(name = "IFlagSfatt", targetNamespace = "")
        String iFlagSfatt,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "IXblnr", targetNamespace = "")
        String iXblnr,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtList", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtList2> etList,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

    /**
     * 
     * @param etMess
     * @param iMailpdf
     * @param iEmail
     * @param iMail
     * @param eEmail
     * @param iPartner
     * @param iDetbol
     * @param eDetbol
     * @param iTipiConto
     * @param eMail
     * @param eMailpdf
     * @param iUpdate
     * @param eReturn
     * @param iCc
     */
    @WebMethod(operationName = "ZptFlagCartaceo")
    @RequestWrapper(localName = "ZptFlagCartaceo", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptFlagCartaceo")
    @ResponseWrapper(localName = "ZptFlagCartaceoResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.test.teaalpenite.ZptFlagCartaceoResponse")
    public void zptFlagCartaceo(
        @WebParam(name = "ICc", targetNamespace = "")
        String iCc,
        @WebParam(name = "IDetbol", targetNamespace = "")
        String iDetbol,
        @WebParam(name = "IEmail", targetNamespace = "")
        String iEmail,
        @WebParam(name = "IMail", targetNamespace = "")
        String iMail,
        @WebParam(name = "IMailpdf", targetNamespace = "")
        String iMailpdf,
        @WebParam(name = "IPartner", targetNamespace = "")
        String iPartner,
        @WebParam(name = "ITipiConto", targetNamespace = "")
        ZptTtVktyp iTipiConto,
        @WebParam(name = "IUpdate", targetNamespace = "")
        String iUpdate,
        @WebParam(name = "EDetbol", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eDetbol,
        @WebParam(name = "EEmail", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eEmail,
        @WebParam(name = "EMail", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMail,
        @WebParam(name = "EMailpdf", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eMailpdf,
        @WebParam(name = "EReturn", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<String> eReturn,
        @WebParam(name = "EtMess", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<ZptTtMess> etMess);

}
