
package com.alpenite.tea.communicationLayer.ws.isu;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-03-03T13:51:16.414+01:00
 * Generated source version: 3.1.5
 * 
 */
public final class ZWSISUPORTAL_ZbnIsuPortal_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSN_ISU_PORTAL");

    private ZWSISUPORTAL_ZbnIsuPortal_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZSNISUPORTAL.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZSNISUPORTAL ss = new ZSNISUPORTAL(wsdlURL, SERVICE_NAME);
        ZWSISUPORTAL port = ss.getZbnIsuPortal();  
        
        {
        System.out.println("Invoking zptContractListDett...");
        java.lang.String _zptContractListDett_iDatafrom = "";
        java.lang.String _zptContractListDett_iDatato = "";
        java.lang.String _zptContractListDett_iFlagPa = "";
        java.lang.String _zptContractListDett_iFlagSfatt = "";
        java.lang.String _zptContractListDett_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptContractListDett_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtList> _zptContractListDett_etList = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtList>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptContractListDett_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptContractListDett(_zptContractListDett_iDatafrom, _zptContractListDett_iDatato, _zptContractListDett_iFlagPa, _zptContractListDett_iFlagSfatt, _zptContractListDett_iPartner, _zptContractListDett_eReturn, _zptContractListDett_etList, _zptContractListDett_etMess);

        System.out.println("zptContractListDett._zptContractListDett_eReturn=" + _zptContractListDett_eReturn.value);
        System.out.println("zptContractListDett._zptContractListDett_etList=" + _zptContractListDett_etList.value);
        System.out.println("zptContractListDett._zptContractListDett_etMess=" + _zptContractListDett_etMess.value);

        }
        {
        System.out.println("Invoking zptSacchetti...");
        java.lang.String _zptSacchetti_iPartner = "";
        java.lang.String _zptSacchetti_iVertrag = "";
        javax.xml.ws.Holder<java.lang.String> _zptSacchetti_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtBidoni> _zptSacchetti_etBidoni = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtBidoni>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptSacchetti_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptSacchetti(_zptSacchetti_iPartner, _zptSacchetti_iVertrag, _zptSacchetti_eReturn, _zptSacchetti_etBidoni, _zptSacchetti_etMess);

        System.out.println("zptSacchetti._zptSacchetti_eReturn=" + _zptSacchetti_eReturn.value);
        System.out.println("zptSacchetti._zptSacchetti_etBidoni=" + _zptSacchetti_etBidoni.value);
        System.out.println("zptSacchetti._zptSacchetti_etMess=" + _zptSacchetti_etMess.value);

        }
        {
        System.out.println("Invoking zsrCadastralDataChange...");
        java.lang.String _zsrCadastralDataChange_iCodCat = "";
        java.lang.String _zsrCadastralDataChange_iComAmm = "";
        java.lang.String _zsrCadastralDataChange_iComCat = "";
        java.lang.String _zsrCadastralDataChange_iPart = "";
        java.lang.String _zsrCadastralDataChange_iPartner = "";
        java.lang.String _zsrCadastralDataChange_iPartst = "";
        java.lang.String _zsrCadastralDataChange_iSezUrb = "";
        java.lang.String _zsrCadastralDataChange_iSubal = "";
        java.lang.String _zsrCadastralDataChange_iTipopar = "";
        java.lang.String _zsrCadastralDataChange_iVertrag = "";
        javax.xml.ws.Holder<java.lang.String> _zsrCadastralDataChange_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zsrCadastralDataChange_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zsrCadastralDataChange(_zsrCadastralDataChange_iCodCat, _zsrCadastralDataChange_iComAmm, _zsrCadastralDataChange_iComCat, _zsrCadastralDataChange_iPart, _zsrCadastralDataChange_iPartner, _zsrCadastralDataChange_iPartst, _zsrCadastralDataChange_iSezUrb, _zsrCadastralDataChange_iSubal, _zsrCadastralDataChange_iTipopar, _zsrCadastralDataChange_iVertrag, _zsrCadastralDataChange_eReturn, _zsrCadastralDataChange_etMess);

        System.out.println("zsrCadastralDataChange._zsrCadastralDataChange_eReturn=" + _zsrCadastralDataChange_eReturn.value);
        System.out.println("zsrCadastralDataChange._zsrCadastralDataChange_etMess=" + _zsrCadastralDataChange_etMess.value);

        }
        {
        System.out.println("Invoking zptDownloadFile...");
        java.lang.String _zptDownloadFile_iArcDocId = "";
        java.lang.String _zptDownloadFile_iPartner = "";
        java.lang.String _zptDownloadFile_iSapObject = "";
        javax.xml.ws.Holder<byte[]> _zptDownloadFile_eBin = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadFile_eExt = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadFile_eMimetyp = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadFile_eName = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadFile_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptDownloadFile_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptDownloadFile(_zptDownloadFile_iArcDocId, _zptDownloadFile_iPartner, _zptDownloadFile_iSapObject, _zptDownloadFile_eBin, _zptDownloadFile_eExt, _zptDownloadFile_eMimetyp, _zptDownloadFile_eName, _zptDownloadFile_eReturn, _zptDownloadFile_etMess);

        System.out.println("zptDownloadFile._zptDownloadFile_eBin=" + _zptDownloadFile_eBin.value);
        System.out.println("zptDownloadFile._zptDownloadFile_eExt=" + _zptDownloadFile_eExt.value);
        System.out.println("zptDownloadFile._zptDownloadFile_eMimetyp=" + _zptDownloadFile_eMimetyp.value);
        System.out.println("zptDownloadFile._zptDownloadFile_eName=" + _zptDownloadFile_eName.value);
        System.out.println("zptDownloadFile._zptDownloadFile_eReturn=" + _zptDownloadFile_eReturn.value);
        System.out.println("zptDownloadFile._zptDownloadFile_etMess=" + _zptDownloadFile_etMess.value);

        }
        {
        System.out.println("Invoking zptLettureSvuotamenti...");
        java.lang.String _zptLettureSvuotamenti_ia = "";
        java.lang.String _zptLettureSvuotamenti_iDa = "";
        java.lang.String _zptLettureSvuotamenti_iFlagLetture = "";
        java.lang.String _zptLettureSvuotamenti_iFlagSac = "";
        java.lang.String _zptLettureSvuotamenti_iFlagSvuota = "";
        java.lang.String _zptLettureSvuotamenti_iPartner = "";
        java.lang.String _zptLettureSvuotamenti_iVertrag = "";
        javax.xml.ws.Holder<java.lang.String> _zptLettureSvuotamenti_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtLett> _zptLettureSvuotamenti_etLett = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtLett>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptLettureSvuotamenti_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptLettureSvuotamenti(_zptLettureSvuotamenti_ia, _zptLettureSvuotamenti_iDa, _zptLettureSvuotamenti_iFlagLetture, _zptLettureSvuotamenti_iFlagSac, _zptLettureSvuotamenti_iFlagSvuota, _zptLettureSvuotamenti_iPartner, _zptLettureSvuotamenti_iVertrag, _zptLettureSvuotamenti_eReturn, _zptLettureSvuotamenti_etLett, _zptLettureSvuotamenti_etMess);

        System.out.println("zptLettureSvuotamenti._zptLettureSvuotamenti_eReturn=" + _zptLettureSvuotamenti_eReturn.value);
        System.out.println("zptLettureSvuotamenti._zptLettureSvuotamenti_etLett=" + _zptLettureSvuotamenti_etLett.value);
        System.out.println("zptLettureSvuotamenti._zptLettureSvuotamenti_etMess=" + _zptLettureSvuotamenti_etMess.value);

        }
        {
        System.out.println("Invoking zptGetBpFromCc...");
        java.lang.String _zptGetBpFromCc_iCc = "";
        try {
            java.lang.String _zptGetBpFromCc__return = port.zptGetBpFromCc(_zptGetBpFromCc_iCc);
            System.out.println("zptGetBpFromCc.result=" + _zptGetBpFromCc__return);

        } catch (ZptGetBpFromCcException e) { 
            System.out.println("Expected exception: ZptGetBpFromCc.Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking zptAutolettura...");
        java.lang.String _zptAutolettura_iAcqua = "";
        java.lang.String _zptAutolettura_iId = "";
        java.lang.String _zptAutolettura_iPartner = "";
        java.lang.String _zptAutolettura_iVertrag = "";
        java.lang.String _zptAutolettura_iZwstan = "";
        javax.xml.ws.Holder<java.lang.String> _zptAutolettura_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptAutolettura_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptAutolettura(_zptAutolettura_iAcqua, _zptAutolettura_iId, _zptAutolettura_iPartner, _zptAutolettura_iVertrag, _zptAutolettura_iZwstan, _zptAutolettura_eReturn, _zptAutolettura_etMess);

        System.out.println("zptAutolettura._zptAutolettura_eReturn=" + _zptAutolettura_eReturn.value);
        System.out.println("zptAutolettura._zptAutolettura_etMess=" + _zptAutolettura_etMess.value);

        }
        {
        System.out.println("Invoking zptReadComune...");
        java.lang.String _zptReadComune_iRegion = "";
        javax.xml.ws.Holder<java.lang.String> _zptReadComune_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtComuni> _zptReadComune_etCity = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtComuni>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptReadComune_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptReadComune(_zptReadComune_iRegion, _zptReadComune_eReturn, _zptReadComune_etCity, _zptReadComune_etMess);

        System.out.println("zptReadComune._zptReadComune_eReturn=" + _zptReadComune_eReturn.value);
        System.out.println("zptReadComune._zptReadComune_etCity=" + _zptReadComune_etCity.value);
        System.out.println("zptReadComune._zptReadComune_etMess=" + _zptReadComune_etMess.value);

        }
        {
        System.out.println("Invoking zptContractDetail...");
        java.lang.String _zptContractDetail_iCc = "";
        java.lang.String _zptContractDetail_iFlagDc = "";
        java.lang.String _zptContractDetail_iFlagInfo = "";
        java.lang.String _zptContractDetail_iFlagPod = "";
        java.lang.String _zptContractDetail_iPartner = "";
        java.lang.String _zptContractDetail_iVertrag = "";
        javax.xml.ws.Holder<java.lang.String> _zptContractDetail_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStDc> _zptContractDetail_esDc = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStDc>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStInfo> _zptContractDetail_esInfo = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStInfo>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStPod> _zptContractDetail_esPod = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStPod>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptContractDetail_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtRiduzioni> _zptContractDetail_etRiduzioni = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtRiduzioni>();
        port.zptContractDetail(_zptContractDetail_iCc, _zptContractDetail_iFlagDc, _zptContractDetail_iFlagInfo, _zptContractDetail_iFlagPod, _zptContractDetail_iPartner, _zptContractDetail_iVertrag, _zptContractDetail_eReturn, _zptContractDetail_esDc, _zptContractDetail_esInfo, _zptContractDetail_esPod, _zptContractDetail_etMess, _zptContractDetail_etRiduzioni);

        System.out.println("zptContractDetail._zptContractDetail_eReturn=" + _zptContractDetail_eReturn.value);
        System.out.println("zptContractDetail._zptContractDetail_esDc=" + _zptContractDetail_esDc.value);
        System.out.println("zptContractDetail._zptContractDetail_esInfo=" + _zptContractDetail_esInfo.value);
        System.out.println("zptContractDetail._zptContractDetail_esPod=" + _zptContractDetail_esPod.value);
        System.out.println("zptContractDetail._zptContractDetail_etMess=" + _zptContractDetail_etMess.value);
        System.out.println("zptContractDetail._zptContractDetail_etRiduzioni=" + _zptContractDetail_etRiduzioni.value);

        }
        {
        System.out.println("Invoking zptBidoni...");
        java.lang.String _zptBidoni_iPartner = "";
        java.lang.String _zptBidoni_iVertrag = "";
        javax.xml.ws.Holder<java.lang.String> _zptBidoni_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtBidoni> _zptBidoni_etBidoni = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtBidoni>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptBidoni_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptBidoni(_zptBidoni_iPartner, _zptBidoni_iVertrag, _zptBidoni_eReturn, _zptBidoni_etBidoni, _zptBidoni_etMess);

        System.out.println("zptBidoni._zptBidoni_eReturn=" + _zptBidoni_eReturn.value);
        System.out.println("zptBidoni._zptBidoni_etBidoni=" + _zptBidoni_etBidoni.value);
        System.out.println("zptBidoni._zptBidoni_etMess=" + _zptBidoni_etMess.value);

        }
        {
        System.out.println("Invoking zptContractList...");
        java.lang.String _zptContractList_iPartner = "";
        com.alpenite.tea.communicationLayer.ws.isu.ZptTtCompanies _zptContractList_itCompany = null;
        javax.xml.ws.Holder<java.lang.String> _zptContractList_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptContractList_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtContract> _zptContractList_itContract = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtContract>();
        port.zptContractList(_zptContractList_iPartner, _zptContractList_itCompany, _zptContractList_eReturn, _zptContractList_etMess, _zptContractList_itContract);

        System.out.println("zptContractList._zptContractList_eReturn=" + _zptContractList_eReturn.value);
        System.out.println("zptContractList._zptContractList_etMess=" + _zptContractList_etMess.value);
        System.out.println("zptContractList._zptContractList_itContract=" + _zptContractList_itContract.value);

        }
        {
        System.out.println("Invoking zptDownloadForm...");
        java.lang.String _zptDownloadForm_iBp = "";
        java.lang.String _zptDownloadForm_iCc = "";
        java.lang.String _zptDownloadForm_isRevoke = "";
        javax.xml.ws.Holder<byte[]> _zptDownloadForm_eBin = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadForm_eExt = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadForm_eMimetyp = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDownloadForm_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptDownloadForm_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptDownloadForm(_zptDownloadForm_iBp, _zptDownloadForm_iCc, _zptDownloadForm_isRevoke, _zptDownloadForm_eBin, _zptDownloadForm_eExt, _zptDownloadForm_eMimetyp, _zptDownloadForm_eReturn, _zptDownloadForm_etMess);

        System.out.println("zptDownloadForm._zptDownloadForm_eBin=" + _zptDownloadForm_eBin.value);
        System.out.println("zptDownloadForm._zptDownloadForm_eExt=" + _zptDownloadForm_eExt.value);
        System.out.println("zptDownloadForm._zptDownloadForm_eMimetyp=" + _zptDownloadForm_eMimetyp.value);
        System.out.println("zptDownloadForm._zptDownloadForm_eReturn=" + _zptDownloadForm_eReturn.value);
        System.out.println("zptDownloadForm._zptDownloadForm_etMess=" + _zptDownloadForm_etMess.value);

        }
        {
        System.out.println("Invoking zptCcListDett...");
        java.lang.String _zptCcListDett_iCc = "";
        java.lang.String _zptCcListDett_iDatafrom = "";
        java.lang.String _zptCcListDett_iDatato = "";
        java.lang.String _zptCcListDett_iFlagEc = "";
        java.lang.String _zptCcListDett_iFlagPa = "";
        java.lang.String _zptCcListDett_iFlagSfatt = "";
        java.lang.String _zptCcListDett_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptCcListDett_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtList> _zptCcListDett_etList = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtList>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptCcListDett_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptCcListDett(_zptCcListDett_iCc, _zptCcListDett_iDatafrom, _zptCcListDett_iDatato, _zptCcListDett_iFlagEc, _zptCcListDett_iFlagPa, _zptCcListDett_iFlagSfatt, _zptCcListDett_iPartner, _zptCcListDett_eReturn, _zptCcListDett_etList, _zptCcListDett_etMess);

        System.out.println("zptCcListDett._zptCcListDett_eReturn=" + _zptCcListDett_eReturn.value);
        System.out.println("zptCcListDett._zptCcListDett_etList=" + _zptCcListDett_etList.value);
        System.out.println("zptCcListDett._zptCcListDett_etMess=" + _zptCcListDett_etMess.value);

        }
        {
        System.out.println("Invoking zptCcDetail...");
        java.lang.String _zptCcDetail_iCc = "";
        java.lang.String _zptCcDetail_iDd = "";
        java.lang.String _zptCcDetail_iDr = "";
        java.lang.String _zptCcDetail_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptCcDetail_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptCcDetail_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStRecapito> _zptCcDetail_isRecapito = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStRecapito>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStRid> _zptCcDetail_isRid = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStRid>();
        port.zptCcDetail(_zptCcDetail_iCc, _zptCcDetail_iDd, _zptCcDetail_iDr, _zptCcDetail_iPartner, _zptCcDetail_eReturn, _zptCcDetail_etMess, _zptCcDetail_isRecapito, _zptCcDetail_isRid);

        System.out.println("zptCcDetail._zptCcDetail_eReturn=" + _zptCcDetail_eReturn.value);
        System.out.println("zptCcDetail._zptCcDetail_etMess=" + _zptCcDetail_etMess.value);
        System.out.println("zptCcDetail._zptCcDetail_isRecapito=" + _zptCcDetail_isRecapito.value);
        System.out.println("zptCcDetail._zptCcDetail_isRid=" + _zptCcDetail_isRid.value);

        }
        {
        System.out.println("Invoking zptFlagCartaceo...");
        java.lang.String _zptFlagCartaceo_iCc = "";
        java.lang.String _zptFlagCartaceo_iDetbol = "";
        java.lang.String _zptFlagCartaceo_iEmail = "";
        java.lang.String _zptFlagCartaceo_iMail = "";
        java.lang.String _zptFlagCartaceo_iMailpdf = "";
        java.lang.String _zptFlagCartaceo_iPartner = "";
        com.alpenite.tea.communicationLayer.ws.isu.ZptTtVktyp _zptFlagCartaceo_iTipiConto = null;
        java.lang.String _zptFlagCartaceo_iUpdate = "";
        javax.xml.ws.Holder<java.lang.String> _zptFlagCartaceo_eDetbol = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptFlagCartaceo_eEmail = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptFlagCartaceo_eMail = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptFlagCartaceo_eMailpdf = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptFlagCartaceo_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptFlagCartaceo_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptFlagCartaceo(_zptFlagCartaceo_iCc, _zptFlagCartaceo_iDetbol, _zptFlagCartaceo_iEmail, _zptFlagCartaceo_iMail, _zptFlagCartaceo_iMailpdf, _zptFlagCartaceo_iPartner, _zptFlagCartaceo_iTipiConto, _zptFlagCartaceo_iUpdate, _zptFlagCartaceo_eDetbol, _zptFlagCartaceo_eEmail, _zptFlagCartaceo_eMail, _zptFlagCartaceo_eMailpdf, _zptFlagCartaceo_eReturn, _zptFlagCartaceo_etMess);

        System.out.println("zptFlagCartaceo._zptFlagCartaceo_eDetbol=" + _zptFlagCartaceo_eDetbol.value);
        System.out.println("zptFlagCartaceo._zptFlagCartaceo_eEmail=" + _zptFlagCartaceo_eEmail.value);
        System.out.println("zptFlagCartaceo._zptFlagCartaceo_eMail=" + _zptFlagCartaceo_eMail.value);
        System.out.println("zptFlagCartaceo._zptFlagCartaceo_eMailpdf=" + _zptFlagCartaceo_eMailpdf.value);
        System.out.println("zptFlagCartaceo._zptFlagCartaceo_eReturn=" + _zptFlagCartaceo_eReturn.value);
        System.out.println("zptFlagCartaceo._zptFlagCartaceo_etMess=" + _zptFlagCartaceo_etMess.value);

        }
        {
        System.out.println("Invoking zptCheckUsername...");
        java.lang.String _zptCheckUsername_iBpType = "";
        java.lang.String _zptCheckUsername_iCc = "";
        java.lang.String _zptCheckUsername_iCf = "";
        java.lang.String _zptCheckUsername_iMail = "";
        java.lang.String _zptCheckUsername_iPi = "";
        javax.xml.ws.Holder<java.lang.String> _zptCheckUsername_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStBpData> _zptCheckUsername_esBpData = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptStBpData>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess> _zptCheckUsername_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.isu.ZptTtMess>();
        port.zptCheckUsername(_zptCheckUsername_iBpType, _zptCheckUsername_iCc, _zptCheckUsername_iCf, _zptCheckUsername_iMail, _zptCheckUsername_iPi, _zptCheckUsername_eReturn, _zptCheckUsername_esBpData, _zptCheckUsername_etMess);

        System.out.println("zptCheckUsername._zptCheckUsername_eReturn=" + _zptCheckUsername_eReturn.value);
        System.out.println("zptCheckUsername._zptCheckUsername_esBpData=" + _zptCheckUsername_esBpData.value);
        System.out.println("zptCheckUsername._zptCheckUsername_etMess=" + _zptCheckUsername_etMess.value);

        }

        System.exit(0);
    }

}
