
package com.alpenite.tea.communicationLayer.ws.crm;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-07-25T00:35:47.341+02:00
 * Generated source version: 2.7.8
 */

@WebFault(name = "ZptGetBpFromCc.Exception", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style")
public class ZptGetBpFromCcException extends Exception {
    
    private com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCcRfcException zptGetBpFromCcException;

    public ZptGetBpFromCcException() {
        super();
    }
    
    public ZptGetBpFromCcException(String message) {
        super(message);
    }
    
    public ZptGetBpFromCcException(String message, Throwable cause) {
        super(message, cause);
    }

    public ZptGetBpFromCcException(String message, com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCcRfcException zptGetBpFromCcException) {
        super(message);
        this.zptGetBpFromCcException = zptGetBpFromCcException;
    }

    public ZptGetBpFromCcException(String message, com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCcRfcException zptGetBpFromCcException, Throwable cause) {
        super(message, cause);
        this.zptGetBpFromCcException = zptGetBpFromCcException;
    }

    public com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCcRfcException getFaultInfo() {
        return this.zptGetBpFromCcException;
    }
}
