package com.alpenite.tea.communicationLayer.ws.crm;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-07-25T00:35:47.353+02:00
 * Generated source version: 2.7.8
 * 
 */
@WebService(targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", name = "ZWS_CRM_PORTAL")
@XmlSeeAlso({ObjectFactory.class})
public interface ZWSCRMPORTAL {

    @RequestWrapper(localName = "ZptBpTypeGet", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBpTypeGet")
    @WebMethod(operationName = "ZptBpTypeGet")
    @ResponseWrapper(localName = "ZptBpTypeGetResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBpTypeGetResponse")
    public void zptBpTypeGet(
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ESapType", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eSapType,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptDeleteUsername", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptDeleteUsername")
    @WebMethod(operationName = "ZptDeleteUsername")
    @ResponseWrapper(localName = "ZptDeleteUsernameResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptDeleteUsernameResponse")
    public void zptDeleteUsername(
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EPartner", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ePartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptBuildingList", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBuildingList")
    @WebMethod(operationName = "ZptBuildingList")
    @ResponseWrapper(localName = "ZptBuildingListResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBuildingListResponse")
    public void zptBuildingList(
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtCondominii", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtCond> etCondominii,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptAddMail", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptAddMail")
    @WebMethod(operationName = "ZptAddMail")
    @ResponseWrapper(localName = "ZptAddMailResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptAddMailResponse")
    public void zptAddMail(
        @WebParam(name = "IEmail", targetNamespace = "")
        java.lang.String iEmail,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptCheckMandAndRevocation", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckMandAndRevocation")
    @WebMethod(operationName = "ZptCheckMandAndRevocation")
    @ResponseWrapper(localName = "ZptCheckMandAndRevocationResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckMandAndRevocationResponse")
    public void zptCheckMandAndRevocation(
        @WebParam(name = "ICc", targetNamespace = "")
        java.lang.String iCc,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(name = "IsMndActive", targetNamespace = "")
        java.lang.String isMndActive,
        @WebParam(name = "IsSrZs09", targetNamespace = "")
        java.lang.String isSrZs09,
        @WebParam(name = "IsSrZs10", targetNamespace = "")
        java.lang.String isSrZs10,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptCreateProspect", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCreateProspect")
    @WebMethod(operationName = "ZptCreateProspect")
    @ResponseWrapper(localName = "ZptCreateProspectResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCreateProspectResponse")
    public void zptCreateProspect(
        @WebParam(name = "IMail", targetNamespace = "")
        java.lang.String iMail,
        @WebParam(name = "IUsername", targetNamespace = "")
        java.lang.String iUsername,
        @WebParam(name = "ItBpData", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData itBpData,
        @WebParam(mode = WebParam.Mode.OUT, name = "EName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eName,
        @WebParam(mode = WebParam.Mode.OUT, name = "EPartner", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ePartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ESurname", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eSurname,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptUploadDocs", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptUploadDocs")
    @WebMethod(operationName = "ZptUploadDocs")
    @ResponseWrapper(localName = "ZptUploadDocsResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptUploadDocsResponse")
    public void zptUploadDocs(
        @WebParam(name = "EtBin", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZbinariesT etBin,
        @WebParam(name = "IBp", targetNamespace = "")
        java.lang.String iBp,
        @WebParam(name = "ICc", targetNamespace = "")
        java.lang.String iCc,
        @WebParam(name = "IsRevoke", targetNamespace = "")
        java.lang.String isRevoke,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptReadBp", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptReadBp")
    @WebMethod(operationName = "ZptReadBp")
    @ResponseWrapper(localName = "ZptReadBpResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptReadBpResponse")
    public void zptReadBp(
        @WebParam(name = "IAzienda", targetNamespace = "")
        java.lang.String iAzienda,
        @WebParam(name = "IJahiaType", targetNamespace = "")
        java.lang.String iJahiaType,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EEmail", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eEmail,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EsBp", targetNamespace = "")
        javax.xml.ws.Holder<ZptStBpData> esBp,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @WebResult(name = "EPartner", targetNamespace = "")
    @RequestWrapper(localName = "ZptGetBpFromCc", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCc")
    @WebMethod(operationName = "ZptGetBpFromCc")
    @ResponseWrapper(localName = "ZptGetBpFromCcResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptGetBpFromCcResponse")
    public java.lang.String zptGetBpFromCc(
        @WebParam(name = "ICc", targetNamespace = "")
        java.lang.String iCc
    ) throws ZptGetBpFromCcException;

    @RequestWrapper(localName = "ZptSrList", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptSrList")
    @WebMethod(operationName = "ZptSrList")
    @ResponseWrapper(localName = "ZptSrListResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptSrListResponse")
    public void zptSrList(
        @WebParam(name = "IDateFrom", targetNamespace = "")
        java.lang.String iDateFrom,
        @WebParam(name = "IDateTo", targetNamespace = "")
        java.lang.String iDateTo,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtSr", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtSr> etSr
    );

    @RequestWrapper(localName = "ZptActivityCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptActivityCreate")
    @WebMethod(operationName = "ZptActivityCreate")
    @ResponseWrapper(localName = "ZptActivityCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptActivityCreateResponse")
    public void zptActivityCreate(
        @WebParam(name = "Category", targetNamespace = "")
        java.lang.String category,
        @WebParam(name = "ContFct", targetNamespace = "")
        java.lang.String contFct,
        @WebParam(name = "ContNo", targetNamespace = "")
        java.lang.String contNo,
        @WebParam(name = "DateFro", targetNamespace = "")
        java.lang.String dateFro,
        @WebParam(name = "DateTo", targetNamespace = "")
        java.lang.String dateTo,
        @WebParam(name = "Descript", targetNamespace = "")
        java.lang.String descript,
        @WebParam(name = "Direct", targetNamespace = "")
        java.lang.String direct,
        @WebParam(name = "Logsys", targetNamespace = "")
        java.lang.String logsys,
        @WebParam(name = "Object", targetNamespace = "")
        java.lang.String object,
        @WebParam(name = "Pdate", targetNamespace = "")
        java.lang.String pdate,
        @WebParam(name = "Priority", targetNamespace = "")
        java.lang.String priority,
        @WebParam(name = "Proctype", targetNamespace = "")
        java.lang.String proctype,
        @WebParam(name = "RespFct", targetNamespace = "")
        java.lang.String respFct,
        @WebParam(name = "RespNo", targetNamespace = "")
        java.lang.String respNo,
        @WebParam(name = "TimeFro", targetNamespace = "")
        java.lang.String timeFro,
        @WebParam(name = "TimeTo", targetNamespace = "")
        java.lang.String timeTo,
        @WebParam(name = "Tzone", targetNamespace = "")
        java.lang.String tzone,
        @WebParam(mode = WebParam.Mode.OUT, name = "EGuid", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eGuid,
        @WebParam(mode = WebParam.Mode.OUT, name = "EObjectId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eObjectId,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptCheckProspect", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckProspect")
    @WebMethod(operationName = "ZptCheckProspect")
    @ResponseWrapper(localName = "ZptCheckProspectResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckProspectResponse")
    public void zptCheckProspect(
        @WebParam(name = "IBpType", targetNamespace = "")
        java.lang.String iBpType,
        @WebParam(name = "IMail", targetNamespace = "")
        java.lang.String iMail,
        @WebParam(name = "IPi", targetNamespace = "")
        java.lang.String iPi,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptBpChange", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBpChange")
    @WebMethod(operationName = "ZptBpChange")
    @ResponseWrapper(localName = "ZptBpChangeResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptBpChangeResponse")
    public void zptBpChange(
        @WebParam(name = "IJahiaType", targetNamespace = "")
        java.lang.String iJahiaType,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(name = "ItBpData", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData itBpData,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptServiceRequestCreate", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptServiceRequestCreate")
    @WebMethod(operationName = "ZptServiceRequestCreate")
    @ResponseWrapper(localName = "ZptServiceRequestCreateResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptServiceRequestCreateResponse")
    public void zptServiceRequestCreate(
        @WebParam(name = "ICateg1", targetNamespace = "")
        java.lang.String iCateg1,
        @WebParam(name = "ICateg2", targetNamespace = "")
        java.lang.String iCateg2,
        @WebParam(name = "IInterloc", targetNamespace = "")
        java.lang.String iInterloc,
        @WebParam(name = "IJahiaType", targetNamespace = "")
        java.lang.String iJahiaType,
        @WebParam(name = "INumciv", targetNamespace = "")
        java.lang.String iNumciv,
        @WebParam(name = "INumcivExtension", targetNamespace = "")
        java.lang.String iNumcivExtension,
        @WebParam(name = "IPartner", targetNamespace = "")
        java.lang.String iPartner,
        @WebParam(name = "IText", targetNamespace = "")
        java.lang.String iText,
        @WebParam(name = "ITypSr", targetNamespace = "")
        java.lang.String iTypSr,
        @WebParam(name = "IVertrag", targetNamespace = "")
        java.lang.String iVertrag,
        @WebParam(name = "IVkont", targetNamespace = "")
        java.lang.String iVkont,
        @WebParam(name = "IsBp", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptStBpData isBp,
        @WebParam(name = "IsCond", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptStCond isCond,
        @WebParam(name = "IsDc", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptStDc isDc,
        @WebParam(name = "IsRec", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptStRecapito isRec,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ESrId", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eSrId,
        @WebParam(mode = WebParam.Mode.OUT, name = "ESrNum", targetNamespace = "")
        javax.xml.ws.Holder<byte[]> eSrNum,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptCreateUsername", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCreateUsername")
    @WebMethod(operationName = "ZptCreateUsername")
    @ResponseWrapper(localName = "ZptCreateUsernameResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCreateUsernameResponse")
    public void zptCreateUsername(
        @WebParam(name = "IBpType", targetNamespace = "")
        java.lang.String iBpType,
        @WebParam(name = "ICc", targetNamespace = "")
        java.lang.String iCc,
        @WebParam(name = "ICf", targetNamespace = "")
        java.lang.String iCf,
        @WebParam(name = "IMail", targetNamespace = "")
        java.lang.String iMail,
        @WebParam(name = "IPi", targetNamespace = "")
        java.lang.String iPi,
        @WebParam(name = "IUnlock", targetNamespace = "")
        java.lang.String iUnlock,
        @WebParam(name = "IUsername", targetNamespace = "")
        java.lang.String iUsername,
        @WebParam(name = "ItBpData", targetNamespace = "")
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData itBpData,
        @WebParam(mode = WebParam.Mode.OUT, name = "EName", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eName,
        @WebParam(mode = WebParam.Mode.OUT, name = "EPartner", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ePartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "ESurname", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eSurname,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );

    @RequestWrapper(localName = "ZptCheckUsername", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckUsername")
    @WebMethod(operationName = "ZptCheckUsername")
    @ResponseWrapper(localName = "ZptCheckUsernameResponse", targetNamespace = "urn:sap-com:document:sap:soap:functions:mc-style", className = "com.alpenite.tea.communicationLayer.ws.crm.ZptCheckUsernameResponse")
    public void zptCheckUsername(
        @WebParam(name = "IBpType", targetNamespace = "")
        java.lang.String iBpType,
        @WebParam(name = "ICc", targetNamespace = "")
        java.lang.String iCc,
        @WebParam(name = "ICf", targetNamespace = "")
        java.lang.String iCf,
        @WebParam(name = "IMail", targetNamespace = "")
        java.lang.String iMail,
        @WebParam(name = "IPi", targetNamespace = "")
        java.lang.String iPi,
        @WebParam(mode = WebParam.Mode.OUT, name = "EPartner", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> ePartner,
        @WebParam(mode = WebParam.Mode.OUT, name = "EReturn", targetNamespace = "")
        javax.xml.ws.Holder<java.lang.String> eReturn,
        @WebParam(mode = WebParam.Mode.OUT, name = "EtMess", targetNamespace = "")
        javax.xml.ws.Holder<ZptTtMess> etMess
    );
}
