
package com.alpenite.tea.communicationLayer.ws.crm;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.8
 * 2014-07-25T00:35:47.193+02:00
 * Generated source version: 2.7.8
 * 
 */
public final class ZWSCRMPORTAL_ZbnCrmPortal_Client {

    private static final QName SERVICE_NAME = new QName("urn:sap-com:document:sap:soap:functions:mc-style", "ZSN_CRM_PORTAL");

    private ZWSCRMPORTAL_ZbnCrmPortal_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ZSNCRMPORTAL.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ZSNCRMPORTAL ss = new ZSNCRMPORTAL(wsdlURL, SERVICE_NAME);
        ZWSCRMPORTAL port = ss.getZbnCrmPortal();  
        
        {
        System.out.println("Invoking zptBpTypeGet...");
        java.lang.String _zptBpTypeGet_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptBpTypeGet_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptBpTypeGet_eSapType = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptBpTypeGet_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptBpTypeGet(_zptBpTypeGet_iPartner, _zptBpTypeGet_eReturn, _zptBpTypeGet_eSapType, _zptBpTypeGet_etMess);

        System.out.println("zptBpTypeGet._zptBpTypeGet_eReturn=" + _zptBpTypeGet_eReturn.value);
        System.out.println("zptBpTypeGet._zptBpTypeGet_eSapType=" + _zptBpTypeGet_eSapType.value);
        System.out.println("zptBpTypeGet._zptBpTypeGet_etMess=" + _zptBpTypeGet_etMess.value);

        }
        {
        System.out.println("Invoking zptDeleteUsername...");
        java.lang.String _zptDeleteUsername_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptDeleteUsername_ePartner = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptDeleteUsername_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptDeleteUsername_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptDeleteUsername(_zptDeleteUsername_iPartner, _zptDeleteUsername_ePartner, _zptDeleteUsername_eReturn, _zptDeleteUsername_etMess);

        System.out.println("zptDeleteUsername._zptDeleteUsername_ePartner=" + _zptDeleteUsername_ePartner.value);
        System.out.println("zptDeleteUsername._zptDeleteUsername_eReturn=" + _zptDeleteUsername_eReturn.value);
        System.out.println("zptDeleteUsername._zptDeleteUsername_etMess=" + _zptDeleteUsername_etMess.value);

        }
        {
        System.out.println("Invoking zptBuildingList...");
        java.lang.String _zptBuildingList_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptBuildingList_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtCond> _zptBuildingList_etCondominii = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtCond>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptBuildingList_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptBuildingList(_zptBuildingList_iPartner, _zptBuildingList_eReturn, _zptBuildingList_etCondominii, _zptBuildingList_etMess);

        System.out.println("zptBuildingList._zptBuildingList_eReturn=" + _zptBuildingList_eReturn.value);
        System.out.println("zptBuildingList._zptBuildingList_etCondominii=" + _zptBuildingList_etCondominii.value);
        System.out.println("zptBuildingList._zptBuildingList_etMess=" + _zptBuildingList_etMess.value);

        }
        {
        System.out.println("Invoking zptAddMail...");
        java.lang.String _zptAddMail_iEmail = "";
        java.lang.String _zptAddMail_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptAddMail_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptAddMail_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptAddMail(_zptAddMail_iEmail, _zptAddMail_iPartner, _zptAddMail_eReturn, _zptAddMail_etMess);

        System.out.println("zptAddMail._zptAddMail_eReturn=" + _zptAddMail_eReturn.value);
        System.out.println("zptAddMail._zptAddMail_etMess=" + _zptAddMail_etMess.value);

        }
        {
        System.out.println("Invoking zptCheckMandAndRevocation...");
        java.lang.String _zptCheckMandAndRevocation_iCc = "";
        java.lang.String _zptCheckMandAndRevocation_iPartner = "";
        java.lang.String _zptCheckMandAndRevocation_isMndActive = "";
        java.lang.String _zptCheckMandAndRevocation_isSrZs09 = "";
        java.lang.String _zptCheckMandAndRevocation_isSrZs10 = "";
        javax.xml.ws.Holder<java.lang.String> _zptCheckMandAndRevocation_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptCheckMandAndRevocation_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptCheckMandAndRevocation(_zptCheckMandAndRevocation_iCc, _zptCheckMandAndRevocation_iPartner, _zptCheckMandAndRevocation_isMndActive, _zptCheckMandAndRevocation_isSrZs09, _zptCheckMandAndRevocation_isSrZs10, _zptCheckMandAndRevocation_eReturn, _zptCheckMandAndRevocation_etMess);

        System.out.println("zptCheckMandAndRevocation._zptCheckMandAndRevocation_eReturn=" + _zptCheckMandAndRevocation_eReturn.value);
        System.out.println("zptCheckMandAndRevocation._zptCheckMandAndRevocation_etMess=" + _zptCheckMandAndRevocation_etMess.value);

        }
        {
        System.out.println("Invoking zptCreateProspect...");
        java.lang.String _zptCreateProspect_iMail = "";
        java.lang.String _zptCreateProspect_iUsername = "";
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData _zptCreateProspect_itBpData = null;
        javax.xml.ws.Holder<java.lang.String> _zptCreateProspect_eName = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateProspect_ePartner = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateProspect_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateProspect_eSurname = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptCreateProspect_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptCreateProspect(_zptCreateProspect_iMail, _zptCreateProspect_iUsername, _zptCreateProspect_itBpData, _zptCreateProspect_eName, _zptCreateProspect_ePartner, _zptCreateProspect_eReturn, _zptCreateProspect_eSurname, _zptCreateProspect_etMess);

        System.out.println("zptCreateProspect._zptCreateProspect_eName=" + _zptCreateProspect_eName.value);
        System.out.println("zptCreateProspect._zptCreateProspect_ePartner=" + _zptCreateProspect_ePartner.value);
        System.out.println("zptCreateProspect._zptCreateProspect_eReturn=" + _zptCreateProspect_eReturn.value);
        System.out.println("zptCreateProspect._zptCreateProspect_eSurname=" + _zptCreateProspect_eSurname.value);
        System.out.println("zptCreateProspect._zptCreateProspect_etMess=" + _zptCreateProspect_etMess.value);

        }
        {
        System.out.println("Invoking zptUploadDocs...");
        com.alpenite.tea.communicationLayer.ws.crm.ZbinariesT _zptUploadDocs_etBin = null;
        java.lang.String _zptUploadDocs_iBp = "";
        java.lang.String _zptUploadDocs_iCc = "";
        java.lang.String _zptUploadDocs_isRevoke = "";
        javax.xml.ws.Holder<java.lang.String> _zptUploadDocs_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptUploadDocs_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptUploadDocs(_zptUploadDocs_etBin, _zptUploadDocs_iBp, _zptUploadDocs_iCc, _zptUploadDocs_isRevoke, _zptUploadDocs_eReturn, _zptUploadDocs_etMess);

        System.out.println("zptUploadDocs._zptUploadDocs_eReturn=" + _zptUploadDocs_eReturn.value);
        System.out.println("zptUploadDocs._zptUploadDocs_etMess=" + _zptUploadDocs_etMess.value);

        }
        {
        System.out.println("Invoking zptReadBp...");
        java.lang.String _zptReadBp_iAzienda = "";
        java.lang.String _zptReadBp_iJahiaType = "";
        java.lang.String _zptReadBp_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptReadBp_eEmail = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptReadBp_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptStBpData> _zptReadBp_esBp = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptStBpData>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptReadBp_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptReadBp(_zptReadBp_iAzienda, _zptReadBp_iJahiaType, _zptReadBp_iPartner, _zptReadBp_eEmail, _zptReadBp_eReturn, _zptReadBp_esBp, _zptReadBp_etMess);

        System.out.println("zptReadBp._zptReadBp_eEmail=" + _zptReadBp_eEmail.value);
        System.out.println("zptReadBp._zptReadBp_eReturn=" + _zptReadBp_eReturn.value);
        System.out.println("zptReadBp._zptReadBp_esBp=" + _zptReadBp_esBp.value);
        System.out.println("zptReadBp._zptReadBp_etMess=" + _zptReadBp_etMess.value);

        }
        {
        System.out.println("Invoking zptGetBpFromCc...");
        java.lang.String _zptGetBpFromCc_iCc = "";
        try {
            java.lang.String _zptGetBpFromCc__return = port.zptGetBpFromCc(_zptGetBpFromCc_iCc);
            System.out.println("zptGetBpFromCc.result=" + _zptGetBpFromCc__return);

        } catch (ZptGetBpFromCcException e) { 
            System.out.println("Expected exception: ZptGetBpFromCc.Exception has occurred.");
            System.out.println(e.toString());
        }
            }
        {
        System.out.println("Invoking zptSrList...");
        java.lang.String _zptSrList_iDateFrom = "";
        java.lang.String _zptSrList_iDateTo = "";
        java.lang.String _zptSrList_iPartner = "";
        javax.xml.ws.Holder<java.lang.String> _zptSrList_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptSrList_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtSr> _zptSrList_etSr = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtSr>();
        port.zptSrList(_zptSrList_iDateFrom, _zptSrList_iDateTo, _zptSrList_iPartner, _zptSrList_eReturn, _zptSrList_etMess, _zptSrList_etSr);

        System.out.println("zptSrList._zptSrList_eReturn=" + _zptSrList_eReturn.value);
        System.out.println("zptSrList._zptSrList_etMess=" + _zptSrList_etMess.value);
        System.out.println("zptSrList._zptSrList_etSr=" + _zptSrList_etSr.value);

        }
        {
        System.out.println("Invoking zptActivityCreate...");
        java.lang.String _zptActivityCreate_category = "";
        java.lang.String _zptActivityCreate_contFct = "";
        java.lang.String _zptActivityCreate_contNo = "";
        java.lang.String _zptActivityCreate_dateFro = "";
        java.lang.String _zptActivityCreate_dateTo = "";
        java.lang.String _zptActivityCreate_descript = "";
        java.lang.String _zptActivityCreate_direct = "";
        java.lang.String _zptActivityCreate_logsys = "";
        java.lang.String _zptActivityCreate_object = "";
        java.lang.String _zptActivityCreate_pdate = "";
        java.lang.String _zptActivityCreate_priority = "";
        java.lang.String _zptActivityCreate_proctype = "";
        java.lang.String _zptActivityCreate_respFct = "";
        java.lang.String _zptActivityCreate_respNo = "";
        java.lang.String _zptActivityCreate_timeFro = "";
        java.lang.String _zptActivityCreate_timeTo = "";
        java.lang.String _zptActivityCreate_tzone = "";
        javax.xml.ws.Holder<java.lang.String> _zptActivityCreate_eGuid = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptActivityCreate_eObjectId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptActivityCreate_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptActivityCreate(_zptActivityCreate_category, _zptActivityCreate_contFct, _zptActivityCreate_contNo, _zptActivityCreate_dateFro, _zptActivityCreate_dateTo, _zptActivityCreate_descript, _zptActivityCreate_direct, _zptActivityCreate_logsys, _zptActivityCreate_object, _zptActivityCreate_pdate, _zptActivityCreate_priority, _zptActivityCreate_proctype, _zptActivityCreate_respFct, _zptActivityCreate_respNo, _zptActivityCreate_timeFro, _zptActivityCreate_timeTo, _zptActivityCreate_tzone, _zptActivityCreate_eGuid, _zptActivityCreate_eObjectId, _zptActivityCreate_etMess);

        System.out.println("zptActivityCreate._zptActivityCreate_eGuid=" + _zptActivityCreate_eGuid.value);
        System.out.println("zptActivityCreate._zptActivityCreate_eObjectId=" + _zptActivityCreate_eObjectId.value);
        System.out.println("zptActivityCreate._zptActivityCreate_etMess=" + _zptActivityCreate_etMess.value);

        }
        {
        System.out.println("Invoking zptCheckProspect...");
        java.lang.String _zptCheckProspect_iBpType = "";
        java.lang.String _zptCheckProspect_iMail = "";
        java.lang.String _zptCheckProspect_iPi = "";
        javax.xml.ws.Holder<java.lang.String> _zptCheckProspect_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptCheckProspect_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptCheckProspect(_zptCheckProspect_iBpType, _zptCheckProspect_iMail, _zptCheckProspect_iPi, _zptCheckProspect_eReturn, _zptCheckProspect_etMess);

        System.out.println("zptCheckProspect._zptCheckProspect_eReturn=" + _zptCheckProspect_eReturn.value);
        System.out.println("zptCheckProspect._zptCheckProspect_etMess=" + _zptCheckProspect_etMess.value);

        }
        {
        System.out.println("Invoking zptBpChange...");
        java.lang.String _zptBpChange_iJahiaType = "";
        java.lang.String _zptBpChange_iPartner = "";
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData _zptBpChange_itBpData = null;
        javax.xml.ws.Holder<java.lang.String> _zptBpChange_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptBpChange_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptBpChange(_zptBpChange_iJahiaType, _zptBpChange_iPartner, _zptBpChange_itBpData, _zptBpChange_eReturn, _zptBpChange_etMess);

        System.out.println("zptBpChange._zptBpChange_eReturn=" + _zptBpChange_eReturn.value);
        System.out.println("zptBpChange._zptBpChange_etMess=" + _zptBpChange_etMess.value);

        }
        {
        System.out.println("Invoking zptServiceRequestCreate...");
        java.lang.String _zptServiceRequestCreate_iCateg1 = "";
        java.lang.String _zptServiceRequestCreate_iCateg2 = "";
        java.lang.String _zptServiceRequestCreate_iInterloc = "";
        java.lang.String _zptServiceRequestCreate_iJahiaType = "";
        java.lang.String _zptServiceRequestCreate_iNumciv = "";
        java.lang.String _zptServiceRequestCreate_iNumcivExtension = "";
        java.lang.String _zptServiceRequestCreate_iPartner = "";
        java.lang.String _zptServiceRequestCreate_iText = "";
        java.lang.String _zptServiceRequestCreate_iTypSr = "";
        java.lang.String _zptServiceRequestCreate_iVertrag = "";
        java.lang.String _zptServiceRequestCreate_iVkont = "";
        com.alpenite.tea.communicationLayer.ws.crm.ZptStBpData _zptServiceRequestCreate_isBp = null;
        com.alpenite.tea.communicationLayer.ws.crm.ZptStCond _zptServiceRequestCreate_isCond = null;
        com.alpenite.tea.communicationLayer.ws.crm.ZptStDc _zptServiceRequestCreate_isDc = null;
        com.alpenite.tea.communicationLayer.ws.crm.ZptStRecapito _zptServiceRequestCreate_isRec = null;
        javax.xml.ws.Holder<java.lang.String> _zptServiceRequestCreate_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptServiceRequestCreate_eSrId = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<byte[]> _zptServiceRequestCreate_eSrNum = new javax.xml.ws.Holder<byte[]>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptServiceRequestCreate_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptServiceRequestCreate(_zptServiceRequestCreate_iCateg1, _zptServiceRequestCreate_iCateg2, _zptServiceRequestCreate_iInterloc, _zptServiceRequestCreate_iJahiaType, _zptServiceRequestCreate_iNumciv, _zptServiceRequestCreate_iNumcivExtension, _zptServiceRequestCreate_iPartner, _zptServiceRequestCreate_iText, _zptServiceRequestCreate_iTypSr, _zptServiceRequestCreate_iVertrag, _zptServiceRequestCreate_iVkont, _zptServiceRequestCreate_isBp, _zptServiceRequestCreate_isCond, _zptServiceRequestCreate_isDc, _zptServiceRequestCreate_isRec, _zptServiceRequestCreate_eReturn, _zptServiceRequestCreate_eSrId, _zptServiceRequestCreate_eSrNum, _zptServiceRequestCreate_etMess);

        System.out.println("zptServiceRequestCreate._zptServiceRequestCreate_eReturn=" + _zptServiceRequestCreate_eReturn.value);
        System.out.println("zptServiceRequestCreate._zptServiceRequestCreate_eSrId=" + _zptServiceRequestCreate_eSrId.value);
        System.out.println("zptServiceRequestCreate._zptServiceRequestCreate_eSrNum=" + _zptServiceRequestCreate_eSrNum.value);
        System.out.println("zptServiceRequestCreate._zptServiceRequestCreate_etMess=" + _zptServiceRequestCreate_etMess.value);

        }
        {
        System.out.println("Invoking zptCreateUsername...");
        java.lang.String _zptCreateUsername_iBpType = "";
        java.lang.String _zptCreateUsername_iCc = "";
        java.lang.String _zptCreateUsername_iCf = "";
        java.lang.String _zptCreateUsername_iMail = "";
        java.lang.String _zptCreateUsername_iPi = "";
        java.lang.String _zptCreateUsername_iUnlock = "";
        java.lang.String _zptCreateUsername_iUsername = "";
        com.alpenite.tea.communicationLayer.ws.crm.ZptTtBpData _zptCreateUsername_itBpData = null;
        javax.xml.ws.Holder<java.lang.String> _zptCreateUsername_eName = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateUsername_ePartner = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateUsername_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCreateUsername_eSurname = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptCreateUsername_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptCreateUsername(_zptCreateUsername_iBpType, _zptCreateUsername_iCc, _zptCreateUsername_iCf, _zptCreateUsername_iMail, _zptCreateUsername_iPi, _zptCreateUsername_iUnlock, _zptCreateUsername_iUsername, _zptCreateUsername_itBpData, _zptCreateUsername_eName, _zptCreateUsername_ePartner, _zptCreateUsername_eReturn, _zptCreateUsername_eSurname, _zptCreateUsername_etMess);

        System.out.println("zptCreateUsername._zptCreateUsername_eName=" + _zptCreateUsername_eName.value);
        System.out.println("zptCreateUsername._zptCreateUsername_ePartner=" + _zptCreateUsername_ePartner.value);
        System.out.println("zptCreateUsername._zptCreateUsername_eReturn=" + _zptCreateUsername_eReturn.value);
        System.out.println("zptCreateUsername._zptCreateUsername_eSurname=" + _zptCreateUsername_eSurname.value);
        System.out.println("zptCreateUsername._zptCreateUsername_etMess=" + _zptCreateUsername_etMess.value);

        }
        {
        System.out.println("Invoking zptCheckUsername...");
        java.lang.String _zptCheckUsername_iBpType = "";
        java.lang.String _zptCheckUsername_iCc = "";
        java.lang.String _zptCheckUsername_iCf = "";
        java.lang.String _zptCheckUsername_iMail = "";
        java.lang.String _zptCheckUsername_iPi = "";
        javax.xml.ws.Holder<java.lang.String> _zptCheckUsername_ePartner = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<java.lang.String> _zptCheckUsername_eReturn = new javax.xml.ws.Holder<java.lang.String>();
        javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess> _zptCheckUsername_etMess = new javax.xml.ws.Holder<com.alpenite.tea.communicationLayer.ws.crm.ZptTtMess>();
        port.zptCheckUsername(_zptCheckUsername_iBpType, _zptCheckUsername_iCc, _zptCheckUsername_iCf, _zptCheckUsername_iMail, _zptCheckUsername_iPi, _zptCheckUsername_ePartner, _zptCheckUsername_eReturn, _zptCheckUsername_etMess);

        System.out.println("zptCheckUsername._zptCheckUsername_ePartner=" + _zptCheckUsername_ePartner.value);
        System.out.println("zptCheckUsername._zptCheckUsername_eReturn=" + _zptCheckUsername_eReturn.value);
        System.out.println("zptCheckUsername._zptCheckUsername_etMess=" + _zptCheckUsername_etMess.value);

        }

        System.exit(0);
    }

}
